spring:
  application:
    name: "locngo"
    frontend:
      url: http://localhost:4200
  datasource:
      url: "jdbc:mysql://localhost:3306/locngo?useSSL=false"
      username: "root"
      password: "root"
  liquibase:
    change-log: classpath:db/liquibase/master.yml
    default-schema: locngo
  servlet:
    multipart:
          enabled: true
          file-size-threshold: 2MB   # au-delà, écrit sur disque temp
          max-file-size: 20MB        # taille max d’un fichier
          max-request-size: 20MB     # taille max de la requête (somme des fichiers)
jwt:
  secret: f75b4b93f2743033db2ea2afe54d586a5cafe34ffe719090c75e0a8cda2930da
  expirationMs: 7200000

links:
    replacement: "https://test-bucket-locngo.s3.eu-north-1.amazonaws.com/1755021331002istockphoto-1409329028-612x612.jpg"
