spring:
  application:
    name: "locngo"
    frontend:
      url: http://localhost:4200
  datasource:
      url: "jdbc:mysql://localhost:3306/locngo?useSSL=false"
      username: "root"
      password: "root"
  liquibase:
    change-log: classpath:db/liquibase/master.yml
    default-schema: locngo
jwt:
  secret: f75b4b93f2743033db2ea2afe54d586a5cafe34ffe719090c75e0a8cda2930da
  expirationMs: 7200000