spring:
  datasource:
    url: jdbc:h2:mem:locngo;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update         # ou create-drop selon ton besoin
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false             # important pour éviter la connexion MySQL
  servlet:
    multipart:
      enabled: true

# Valeurs bidon pour éviter d'avoir à fournir des secrets en test
jwt:
  secret: testsecret
  expirationMs: 7200000
