name: Java Tests

on:
  pull_request:
    branches: [develop, master, main]
  push:
    branches: [develop, master, main, 'feature/**']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run unit tests only
        run: mvn -B -ntp test -Dspring.profiles.active=test